package com.pomodoro.app.enums;

public enum GoalEventType {
  GOAL_CREATED,
  COMMITMENT_CREATED,
  FOCUS_SESSION_STARTED,
  FOCUS_SESSION_COMPLETED,
  REPORT_SUBMITTED,
  REPORT_APPROVED,
  REPORT_REJECTED,
  REPORT_NEEDS_MORE_INFO,
  DAY_COMPLETED,
  DAY_MISSED,
  STREAK_UPDATED,
  DISCIPLINE_SCORE_CHANGED,
  RISK_STATUS_CHANGED,
  REWARD_UNLOCKED,
  MONEY_PENALTY_CHARGED,
  MONEY_EMPTY,
  AI_RECOMMENDATION_CREATED
}
