package com.pomodoro.app.enums;

public enum MotivationImageReportReason {
  NSFW,
  IRRELEVANT_TO_GOAL,
  INAPPROPRIATE_IMAGE,
  INAPPROPRIATE_TEXT,
  REPEATS_TOO_OFTEN,
  INAPPROPRIATE,
  UNPLEASANT,
  OFFENSIVE,
  LOW_QUALITY,
  IRRELEVANT,
  DUPLICATE,
  BROKEN_IMAGE,
  SPAM,
  OTHER
}
